name: Axialy DB AWS            # clearer workflow name
on:
  workflow_dispatch:
    inputs:
      db_identifier:
        description: "RDS identifier prefix"
        required: true
        default: axialy-db
      region:
        description: "AWS region"
        required: true
        default: us-west-2
      db_instance_class:
        description: "RDS instance class"
        required: true
        default: db.t3.micro
      db_allocated_storage:
        description: "Allocated storage (GB)"
        required: true
        default: "20"

jobs:
  apply:
    runs-on: ubuntu-24.04
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:    ${{ inputs.region }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: infra/rds

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Terraform init
        run: terraform -chdir=infra/rds init -input=false

      - name: Terraform validate          # <-- NEW
        run: terraform -chdir=infra/rds validate

      - name: Terraform apply
        id: tf
        run: |
          terraform -chdir=infra/rds apply -auto-approve -input=false \
            -var="db_identifier=${{ inputs.db_identifier }}" \
            -var="region=${{ inputs.region }}" \
            -var="db_instance_class=${{ inputs.db_instance_class }}" \
            -var="db_allocated_storage=${{ inputs.db_allocated_storage }}"

          echo "DB_HOST=$(terraform  -chdir=infra/rds output -raw db_host)"      >> $GITHUB_ENV
          echo "UI_DB_HOST=$(terraform -chdir=infra/rds output -raw ui_db_host)" >> $GITHUB_ENV
          echo "DB_PORT=$(terraform   -chdir=infra/rds output -raw db_port)"     >> $GITHUB_ENV
          echo "DB_USER=$(terraform   -chdir=infra/rds output -raw db_user)"     >> $GITHUB_ENV
          echo "DB_PASSWORD=$(terraform -chdir=infra/rds output -raw db_pass)"   >> $GITHUB_ENV

      # optional secret-persist step stays unchanged
