name: Axialy Admin on AWS

on:
  workflow_dispatch:    # manual-only trigger

jobs:
  noop:                 # a single, do-nothing job
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Axialy Admin on AWS manual workflow stub – works!"
